version: "3.8"
services:
  gateway:
    image: nginx:1.19.8-alpine
    ports:
      - 8080:8080
    networks:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./api_gateway.conf:/etc/nginx/api_gateway.conf
  
  media-service-mysql:
    image: mysql:5.6.27
    ports:
      - 3306:3306
    volumes:
      - media_service_mysqldata:/var/lib/mysql
      - ./resources/initdb_media_service:/docker-entrypoint-initdb.d
    container_name: mysql-nistagram-media-service
    environment:
        MYSQL_ROOT_PASSWORD: root
    networks:
      - backend

  media-service:
    depends_on: 
      - media-service-mysql
    # image: borisns/nistagram-media-service
    build:
      context: ../nistagram-media-service
      dockerfile: Dockerfile
    ports:
      - 9000:8000
    networks:
      - backend  

networks:
  backend:
    name: nistagram
    driver: bridge

volumes:
  media_service_mysqldata:
    driver: local
    