version: "3.8"
services:
  gateway:
    image: nginx:1.19.8-alpine
    ports:
      - 8080:8080
    networks:
      - backend
    volumes:
      - ../nistagram-api-gateway/nginx.conf:/etc/nginx/nginx.conf
      - ../nistagram-api-gateway/api_gateway.conf:/etc/nginx/api_gateway.conf
  
  media-service-mysql:
    image: mysql:5.6.27
    ports:
      - 3306:3306
    volumes:
      - media_service_mysqldata:/var/lib/mysql
      - ./resources/initdb_media_service:/docker-entrypoint-initdb.d
    container_name: mysql-nistagram-media-service
    environment:
        MYSQL_ROOT_PASSWORD: root
    networks:
      - backend

  media-service:
    depends_on: 
      - media-service-mysql
      - prometheus
    # image: borisns/nistagram-media-service
    build:
      context: ../nistagram-media-service
      dockerfile: Dockerfile
    ports:
      - 9000:8000
    networks:
      - backend  

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: on-failure
    networks:
      - backend
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana:7.5.2
    container_name: grafana
    depends_on:
      - prometheus
    restart: on-failure
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - backend
    ports:
      - 3000:3000
    volumes: []

networks:
  backend:
    name: nistagram
    driver: bridge

volumes:
  media_service_mysqldata:
    driver: local
    