  # my global config
  global:
    scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
    evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
    # scrape_timeout is set to the global default (10s).

  scrape_configs:
    - job_name: 'prometheus'

      # metrics_path defaults to '/metrics'
      # scheme defaults to 'http'.
      static_configs:
        - targets: ['localhost:9090']

    # - job_name: 'app'
    #   static_configs:
    #     - targets: ['app:8080']

    - job_name: 'media-service'
      static_configs:
        - targets: ['media-service:9000']

    - job_name: 'post-service'
      static_configs:
        - targets: ['post-service:9001']

    - job_name: 'user-service'
      static_configs:
        - targets: ['user-service:9002']

    - job_name: 'campaign-service'
      static_configs:
        - targets: ['campaign-service:9004']

    - job_name: 'node_exporter'
      static_configs:
        - targets: [ 'node-exporter:9100' ]

    - job_name: 'grafana'
      static_configs:
        - targets: ['grafana:3000']
